export const questionnaireSections = [
  {
    key: 'general',
    title: 'Información general',
    description: 'Empecemos con los datos básicos del restaurante y de la persona de contacto.',
    fields: [
      { name: 'restaurantName', label: 'Nombre del restaurante', type: 'text' },
      { name: 'contactName', label: 'Nombre del responsable', type: 'text' },
      { name: 'contactRole', label: 'Cargo del responsable', type: 'text' },
      { name: 'phone', label: 'Teléfono', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp', type: 'text' },
      { name: 'email', label: 'Correo electrónico', type: 'email' },
      { name: 'address', label: 'Dirección completa', type: 'text' },
      { name: 'mapsUrl', label: 'Enlace Google Maps', type: 'url' },
      { name: 'city', label: 'Ciudad', type: 'text' },
      { name: 'country', label: 'País', type: 'text' },
    ],
  },
  {
    key: 'branding',
    title: 'Identidad y branding',
    description: 'Aquí recopilamos el carácter del local: estilo, tono, colores e historia.',
    fields: [
      { name: 'shortDescription', label: 'Descripción breve del restaurante', type: 'textarea' },
      { name: 'restaurantStory', label: 'Historia del restaurante', type: 'textarea' },
      { name: 'cuisineType', label: 'Tipo de cocina', type: 'text' },
      { name: 'restaurantStyle', label: 'Estilo del local', type: 'text' },
      { name: 'communicationTone', label: 'Tono comunicativo', type: 'text' },
      { name: 'mainColors', label: 'Colores principales', type: 'text' },
      { name: 'hasLogo', label: '¿Tienes logo disponible?', type: 'select', options: ['Sí', 'No'] },
      { name: 'slogan', label: 'Slogan o frase principal', type: 'text' },
      { name: 'wordsToAvoid', label: 'Palabras que debemos evitar', type: 'textarea' },
    ],
  },
  {
    key: 'hours',
    title: 'Horarios y operativa',
    description: 'Indica cuándo está abierto el restaurante y los horarios especiales.',
    fields: [
      { name: 'monday', label: 'Lunes', type: 'textarea' },
      { name: 'tuesday', label: 'Martes', type: 'textarea' },
      { name: 'wednesday', label: 'Miércoles', type: 'textarea' },
      { name: 'thursday', label: 'Jueves', type: 'textarea' },
      { name: 'friday', label: 'Viernes', type: 'textarea' },
      { name: 'saturday', label: 'Sábado', type: 'textarea' },
      { name: 'sunday', label: 'Domingo', type: 'textarea' },
      { name: 'kitchenClosing', label: 'Hora de cierre de cocina', type: 'text' },
      { name: 'specialDays', label: 'Festivos u horarios especiales', type: 'textarea' },
    ],
  },
]