export const questionnaireSections = [
  {
    key: 'general',
    title: 'Información general',
    description: 'Empecemos con los datos básicos del restaurante y de la persona de contacto.',
    fields: [
      { name: 'restaurantName', label: 'Nombre del restaurante', type: 'text' },
      { name: 'contactName', label: 'Nombre del responsable', type: 'text' },
      { name: 'contactRole', label: 'Cargo del responsable', type: 'text' },
      { name: 'phone', label: 'Teléfono', type: 'text' },
      { name: 'whatsapp', label: 'WhatsApp', type: 'text' },
      { name: 'email', label: 'Correo electrónico', type: 'email' },
      { name: 'address', label: 'Dirección completa', type: 'text' },
      { name: 'mapsUrl', label: 'Enlace Google Maps', type: 'url' },
      { name: 'city', label: 'Ciudad', type: 'text' },
      { name: 'country', label: 'País', type: 'text' },
    ],
  },
  {
    key: 'branding',
    title: 'Identidad y branding',
    description: 'Aquí recopilamos el carácter del local: estilo, tono, colores e historia.',
    fields: [
      { name: 'shortDescription', label: 'Descripción breve del restaurante', type: 'textarea' },
      { name: 'restaurantStory', label: 'Historia del restaurante', type: 'textarea' },
      { name: 'cuisineType', label: 'Tipo de cocina', type: 'text' },
      { name: 'restaurantStyle', label: 'Estilo del local', type: 'text' },
      { name: 'communicationTone', label: 'Tono comunicativo', type: 'text' },
      { name: 'mainColors', label: 'Colores principales', type: 'text' },
      { name: 'hasLogo', label: '¿Tienes logo disponible?', type: 'select', options: ['Sí', 'No'] },
      { name: 'slogan', label: 'Slogan o frase principal', type: 'text' },
      { name: 'wordsToAvoid', label: 'Palabras que debemos evitar', type: 'textarea' },
    ],
  },
  {
    key: 'hours',
    title: 'Horarios y operativa',
    description: 'Indica cuándo está abierto el restaurante y los horarios especiales.',
    fields: [
      { name: 'monday', label: 'Lunes', type: 'textarea' },
      { name: 'tuesday', label: 'Martes', type: 'textarea' },
      { name: 'wednesday', label: 'Miércoles', type: 'textarea' },
      { name: 'thursday', label: 'Jueves', type: 'textarea' },
      { name: 'friday', label: 'Viernes', type: 'textarea' },
      { name: 'saturday', label: 'Sábado', type: 'textarea' },
      { name: 'sunday', label: 'Domingo', type: 'textarea' },
      { name: 'kitchenClosing', label: 'Hora de cierre de cocina', type: 'text' },
      { name: 'specialDays', label: 'Festivos u horarios especiales', type: 'textarea' },
    ],
  },
  {
    key: 'spaces',
    title: 'Espacios, mesas y capacidad',
    description: 'Describe las zonas del restaurante, número de mesas y capacidad aproximada.',
    fields: [
      { name: 'indoorArea', label: 'Sala interior', type: 'textarea' },
      { name: 'terraceArea', label: 'Terraza', type: 'textarea' },
      { name: 'barArea', label: 'Barra', type: 'textarea' },
      { name: 'privateArea', label: 'Zona privada o reservable', type: 'textarea' },
      { name: 'tablesNumber', label: 'Número total de mesas', type: 'number' },
      { name: 'seatsPerTable', label: 'Puestos por mesa / distribución', type: 'textarea' },
      { name: 'combinableTables', label: '¿Se pueden combinar mesas?', type: 'select', options: ['Sí', 'No', 'Depende'] },
      { name: 'maxCapacity', label: 'Capacidad máxima aproximada', type: 'number' },
      { name: 'averageTableTime', label: 'Tiempo medio por mesa', type: 'text' },
    ],
  },
  {
    key: 'menu',
    title: 'Menú',
    description: 'Introduce las categorías principales y la información base de los platos. Si ya tienes el menú, puedes describirlo aquí por bloques.',
    fields: [
      { name: 'menuCategories', label: 'Categorías del menú', type: 'textarea' },
      { name: 'signatureDishes', label: 'Platos recomendados o estrella', type: 'textarea' },
      { name: 'menuItemsDraft', label: 'Lista de platos con descripción, ingredientes y precio', type: 'textarea' },
      { name: 'vegetarianOptions', label: 'Platos vegetarianos', type: 'textarea' },
      { name: 'veganOptions', label: 'Platos veganos', type: 'textarea' },
      { name: 'glutenFreeOptions', label: 'Platos sin gluten o adaptables', type: 'textarea' },
      { name: 'spicyOptions', label: 'Platos picantes', type: 'textarea' },
      { name: 'preparationTimes', label: 'Tiempos de preparación importantes', type: 'textarea' },
      { name: 'foodCostNotes', label: 'Food cost estimado o notas de costes', type: 'textarea' },
      { name: 'existingMenuNotes', label: '¿Tienes menú en PDF, Excel o imagen?', type: 'textarea' },
    ],
  },
  {
    key: 'allergens',
    title: 'Alérgenos e intolerancias',
    description: 'Indica alérgenos importantes, opciones adaptables y riesgos de contaminación cruzada.',
    fields: [
      { name: 'glutenNotes', label: 'Gluten', type: 'textarea' },
      { name: 'lactoseNotes', label: 'Lactosa / lácteos', type: 'textarea' },
      { name: 'eggNotes', label: 'Huevos', type: 'textarea' },
      { name: 'fishNotes', label: 'Pescado', type: 'textarea' },
      { name: 'seafoodNotes', label: 'Crustáceos / moluscos', type: 'textarea' },
      { name: 'nutsNotes', label: 'Frutos secos / cacahuetes', type: 'textarea' },
      { name: 'soyNotes', label: 'Soja', type: 'textarea' },
      { name: 'otherAllergens', label: 'Otros alérgenos: apio, mostaza, sésamo, sulfitos, altramuces', type: 'textarea' },
      { name: 'crossContamination', label: 'Contaminación cruzada', type: 'textarea' },
      { name: 'sharedFryer', label: '¿Hay freidora compartida?', type: 'select', options: ['Sí', 'No', 'No estoy seguro'] },
      { name: 'adaptableOptions', label: 'Opciones adaptables para intolerancias', type: 'textarea' },
    ],
  },
  {
    key: 'drinks',
    title: 'Bebidas, vinos y cócteles',
    description: 'Recopilamos la carta líquida: vinos, cócteles, cervezas, refrescos y posibles reglas de venta.',
    fields: [
      { name: 'redWines', label: 'Vinos tintos', type: 'textarea' },
      { name: 'whiteWines', label: 'Vinos blancos', type: 'textarea' },
      { name: 'roseWines', label: 'Vinos rosados', type: 'textarea' },
      { name: 'sparklingWines', label: 'Espumosos', type: 'textarea' },
      { name: 'cocktails', label: 'Cócteles', type: 'textarea' },
      { name: 'beers', label: 'Cervezas', type: 'textarea' },
      { name: 'softDrinks', label: 'Refrescos / agua / bebidas sin alcohol', type: 'textarea' },
      { name: 'glassPrices', label: 'Precios por copa', type: 'textarea' },
      { name: 'bottlePrices', label: 'Precios por botella', type: 'textarea' },
      { name: 'purchaseCosts', label: 'Coste de compra si se conoce', type: 'textarea' },
      { name: 'pairingNotes', label: 'Maridajes recomendados', type: 'textarea' },
    ],
  },
  {
    key: 'bookings',
    title: 'Reservas',
    description: 'Define cómo debe comportarse el sistema de reservas y qué reglas debe respetar.',
    fields: [
      { name: 'acceptOnlineBookings', label: '¿Aceptas reservas online?', type: 'select', options: ['Sí', 'No', 'Más adelante'] },
      { name: 'confirmationMode', label: 'Tipo de confirmación', type: 'select', options: ['Automática', 'Manual', 'Depende del horario'] },
      { name: 'maxOnlineGuests', label: 'Máximo de personas por reserva online', type: 'number' },
      { name: 'minAdvanceTime', label: 'Antelación mínima para reservar', type: 'text' },
      { name: 'cancellationPolicy', label: 'Política de cancelación', type: 'textarea' },
      { name: 'largeGroupsPolicy', label: 'Reglas para grupos grandes', type: 'textarea' },
      { name: 'privateEvents', label: 'Eventos privados', type: 'textarea' },
      { name: 'bookingCustomerNotes', label: 'Notas visibles para el cliente', type: 'textarea' },
    ],
  },
  {
    key: 'faq',
    title: 'FAQ del restaurante',
    description: 'Preguntas frecuentes para alimentar la web y el futuro chatbot del restaurante.',
    fields: [
      { name: 'dogsAllowed', label: '¿Aceptáis perros?', type: 'textarea' },
      { name: 'hasTerrace', label: '¿Tenéis terraza?', type: 'textarea' },
      { name: 'vegetarianFaq', label: 'Opciones vegetarianas', type: 'textarea' },
      { name: 'veganFaq', label: 'Opciones veganas', type: 'textarea' },
      { name: 'glutenFreeFaq', label: 'Opciones sin gluten', type: 'textarea' },
      { name: 'takeawayFaq', label: 'Take away', type: 'textarea' },
      { name: 'deliveryFaq', label: 'Delivery', type: 'textarea' },
      { name: 'groupsFaq', label: 'Grupos y cumpleaños', type: 'textarea' },
      { name: 'paymentMethods', label: 'Métodos de pago', type: 'textarea' },
      { name: 'accessibility', label: 'Accesibilidad', type: 'textarea' },
      { name: 'parking', label: 'Parking', type: 'textarea' },
      { name: 'spokenLanguages', label: 'Idiomas hablados', type: 'textarea' },
      { name: 'customFaq', label: 'Otras preguntas frecuentes importantes', type: 'textarea' },
    ],
  },
  {
    key: 'materials',
    title: 'Fotos y materiales',
    description: 'Indica qué materiales existen y qué falta preparar. El upload real lo añadiremos en la siguiente fase.',
    fields: [
      { name: 'logoFiles', label: 'Logo disponible', type: 'textarea' },
      { name: 'exteriorPhotos', label: 'Fotos del exterior', type: 'textarea' },
      { name: 'interiorPhotos', label: 'Fotos del interior', type: 'textarea' },
      { name: 'dishPhotos', label: 'Fotos de platos', type: 'textarea' },
      { name: 'drinkPhotos', label: 'Fotos de bebidas', type: 'textarea' },
      { name: 'staffPhotos', label: 'Fotos del equipo', type: 'textarea' },
      { name: 'atmospherePhotos', label: 'Fotos de ambiente', type: 'textarea' },
      { name: 'existingMenuFiles', label: 'Menú existente', type: 'textarea' },
      { name: 'wineMenuFiles', label: 'Carta de vinos existente', type: 'textarea' },
      { name: 'brandManual', label: 'Manual de marca o referencias visuales', type: 'textarea' },
    ],
  },
  {
    key: 'socials',
    title: 'Social, reseñas y contacto',
    description: 'Enlaces públicos, redes sociales y plataformas de reseñas.',
    fields: [
      { name: 'instagram', label: 'Instagram', type: 'url' },
      { name: 'facebook', label: 'Facebook', type: 'url' },
      { name: 'tiktok', label: 'TikTok', type: 'url' },
      { name: 'googleBusiness', label: 'Google Business / Google Reviews', type: 'url' },
      { name: 'tripadvisor', label: 'Tripadvisor', type: 'url' },
      { name: 'theFork', label: 'TheFork', type: 'url' },
      { name: 'currentWebsite', label: 'Web actual', type: 'url' },
      { name: 'publicEmail', label: 'Email público', type: 'email' },
      { name: 'publicPhone', label: 'Teléfono público', type: 'text' },
      { name: 'publicWhatsapp', label: 'WhatsApp público', type: 'text' },
    ],
  },
  {
    key: 'features',
    title: 'Funciones Menuria deseadas',
    description: 'Selecciona o describe las funciones que te interesan para este proyecto.',
    fields: [
      { name: 'wantedFeatures', label: 'Funciones deseadas: menú QR, traducciones, alérgenos, chatbot, reservas, dashboard, QR mesas, analytics, carta vinos, takeaway, etc.', type: 'textarea' },
      { name: 'priorityFeatures', label: 'Funciones prioritarias para el lanzamiento', type: 'textarea' },
      { name: 'futureFeatures', label: 'Funciones que podrían añadirse más adelante', type: 'textarea' },
      { name: 'budgetRange', label: 'Rango de presupuesto orientativo', type: 'text' },
      { name: 'launchDeadline', label: 'Fecha ideal de lanzamiento', type: 'date' },
      { name: 'extraNotes', label: 'Notas finales para Menuria Solutions', type: 'textarea' },
    ],
  },
]